Project start
coachmatt-io/fe-projects pull request #2
Opened 2022-03-07 01:20 UTC by ramseylove

Have the main functionality working. Minimal styling but other than that im pretty happy with everything. Changed the layout a few times. Decided I wanted the player out of the browsing window, so I put it in the header. Then I didn't know where I wanted to put each episodes details, so I put that in a modal.

Need to start the json-server along with the react-scripts with `npm run dev` otherwise there will not be any shows. Also Episodes are being limited to only 10 right now.

todos:
styling could be made responsive
pagination of episodes.

possible todos:
integrate with live podcast api to get shows
search functionality

2022-03-07 18:01 UTC, matthewoates requested changes

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/README.md
> +podcasts: [
This isn't valid JSON. See how everything is highlighted in red?

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/data/episodes.js
> +const episodes = {
Any reason you hardcoded all of this data? It's already being fetched live on the client.

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/data/server.js
> +// var episodes = require("./episodes.json");
[Commented code is still code](https://kentcdodds.com/blog/please-dont-commit-commented-out-code), and reduces maintainability.

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/utils/api-utils.js
> +      pubDate: parseDate(parsedXml.rss.channel.pubDate),
I'm getting an error on this line when I try to load `The Apology Line`.

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/assets/SVG/circle-right.svg
> +<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
Where'd you find these assets? Including assets like this is fine, but there's a little more overhead. Namely - Is the license reflected anywhere? A lot of people use `react-icons` which is multiple large collections of icons.

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/components/episode/EpisodeDetails.jsx
> +function EpisodeDetails({ episode, setSelectedEpisodePlaying }) {
Dead code

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/components/episode/EpisodeList.jsx
> +  const [selectedShow, setSelectedShow] = useState({});
I feel like `null` is a more semantically appropriate default state value here.

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/components/episode/EpisodeModal.jsx
> +import { ReactComponent as PlayButton } from "../../assets/SVG/play2.svg";
This isn't a button, it's an icon

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/components/episode/EpisodeModal.jsx
> +import React from "react";
React tooling doesn't require you to import `React` anymore

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/components/episode/EpisodePlayer.jsx
> +function EpisodePlayer({ episode }) {
Stupid simple. It works!

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/components/header.jsx
> +    <div className="header">
You can [use more semantically appropriate HTML elements](https://developer.mozilla.org/en-US/docs/Glossary/Semantics#semantic_elements). For this, I'd use the `<header>` tag.

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/components/header.jsx
> +      <h3>Ultimate Podcasting</h3>
Expanding on HTML semantics, [your header tags should follow a clear h1-h2-h3-... hierarchy](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements). If you want a different style don't use a different tag - style the tag.

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/components/show/Show.jsx
> +function Show({ id, title, feed, selectShow }) {
Lots of these props aren't used.

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/components/show/ShowList.jsx
> +          key={show.id}
Good key usage. I've seen messaging apps built where they use `key={index}` which will force React to do a lot of work if any of the messages move to another index in the array.

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/globals.css
> +body {
Not going to dive into this - there's so many ways to style React apps, and very few people use vanilla CSS. Given the current scope of the project vanilla CSS is great (Keep It Simple Stupid) but if you'd like to chat more about alternative styling solutions let me know.

Currently, I'm trying out [Linaria](https://github.com/callstack/linaria), which is very similar to [styled-components](https://styled-components.com/). The big pro behind Linaria is that it's zero-runtime. Styled-components does a lot of work on the client-side to parse the styles into something useable by the browser, while Linaria does all of the heavy lifting at build time.

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/utils/api-utils.js
> +  const url = "http://localhost:3500/podcasts";
Dead code? `localhost` isn't going to work in prod.

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/utils/utils.js
> +export function parseDate(str) {
Ah - I forgot podcast descriptions can include HTML. Assuming this doesn't introduce any XSS vulnerabilities, it doesn't like unmatched `<` symbols.

`removeHtml('this < that') === 'this '`

Writing your own HTML sanitizer / stripper is incredibly difficult, dangerous, and complex. If you introduce an XSS vulnerability, your whole app is compromised. You also have to worry about handling malformed inputs. RSS XML data is structured, but the description can be an arbitrary string. You can't assume it's going to be well formed.

I'd immediately reject any homebrew solution to validate or sanitize HTML. Some digging found this solution using `DOMParser`: https://stackoverflow.com/a/47140708/1388336

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/utils/api-utils.js
> +      episodes: [...cleanedEpisodes],
No need to make a shallow copy of this

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/components/episode/EpisodeModal.jsx
> +const ModalOverlay = ({
Interesting that you implemented your own modal. Finding a good component library can be hard.

Modals are notoriously difficult to get right. A good library will handle complex cases out of the box such as keyboard focus trapping and smaller screen sizes (eg: mobile)

2022-03-07 18:01 UTC, matthewoates commented on podcast-player/podcast-player-app/src/components/episode/EpisodePlayer.jsx
> +        src={episode.enclosure.$url}
If we're already massaging the parsed XML data, we should probably also transform the episode data into a more useable shape.

2022-03-07 18:05 UTC, matthewoates commented
This is legit. ~~I wasn't able to find any bugs~~. I only found one bug, but it's a big one. There's some UX limitations, and after looking at the code some big technical limitations as well. I'm listening to one of the episodes as I write this code review.

From a UX perspective before looking at any of the code:

- 👍👍 Live demo! This makes review so much easier.
- ~~👍👍 No bugs found!~~ 👎👎 The Apology Line fails to load, and there's no error state to indicate that
- 👍👍 persistent player. I can continue listening to a podcast while I browse
- 👍👍 loading indicators (not pretty, but we're not showing something bogus like "no episodes" while episodes are loading)
- 👍 clean approachable (but not pretty) UI. A Hacker News vibe
- 👎 no visual reflection of selected show or episode within the lists
- 👎👎 no routing / persistence of state via the URL. If you refresh, you're back at the homepage. You can't share a link to an episode with anyone.

And looking at the code, see inline comments + these notes:
- 👎 The folder structure is a little funny. `podcast-player/podcast-player/README.md`. Unnecessarily deep file structures add bloat to projects. The instructions suggest putting everything directly in the `podcast-player` folder.
- 👎👎 RSS feed data is hardcoded in the codebase, but we're also fetching the data on the client-side. Why is this hardcoded?

---

Hopefully you found this to be a valuable exercise. If you're still pumped about this project and would like to take it to the next level, the most notable improvements to make from my perspective are:

- add podcast search (I spent a few minutes looking for a podcast search API but nothing jumped out at me. This also adds a lot of complexity to the project since you'd probably what to make a server. This allows you to hide your API key)
- Use a UI component library. Designing a good looking and functional app from scratch is a pretty big ask and demands a lot of different skills. You can of course use other apps as reference. When it comes to implementation, the React UI libraries I've enjoyed working with are [material-ui](https://github.com/mui/material-ui) and [mantine](https://github.com/mantinedev/mantine).

2022-03-07 20:15 UTC, ramseylove commented on podcast-player/podcast-player-app/README.md
> +podcasts: [
changed to js, but then now removed this readme

2022-03-07 20:16 UTC, ramseylove commented on podcast-player/podcast-player-app/data/episodes.js
> +const episodes = {
unused file relating to local xml dummy server

2022-03-07 20:17 UTC, ramseylove commented on podcast-player/podcast-player-app/data/server.js
> +// var episodes = require("./episodes.json");
deleted with cleanup

2022-03-07 20:18 UTC, ramseylove commented on podcast-player/podcast-player-app/src/utils/api-utils.js
> +      pubDate: parseDate(parsedXml.rss.channel.pubDate),
Now only running parseDate if pubDate exists on show

2022-03-07 20:25 UTC, ramseylove commented on podcast-player/podcast-player-app/src/components/episode/EpisodeDetails.jsx
> +function EpisodeDetails({ episode, setSelectedEpisodePlaying }) {
yup but thinking I might make a different view of the episode info, expanded from modal view but with more data. not sure. do

2022-03-07 20:26 UTC, ramseylove commented on podcast-player/podcast-player-app/src/assets/SVG/circle-right.svg
> +<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
These are from icomoon.io, the free icons. Where do you recommend putting license info for things used on a site that I did not create? As they do not have any info the code you copy from them.

2022-03-07 20:45 UTC, ramseylove commented on podcast-player/podcast-player-app/src/components/episode/EpisodeList.jsx
> +  const [selectedShow, setSelectedShow] = useState({});
for the selectedShow state, I would need set the show data to the state without using the spread syntax. I get an error with it set to null

2022-03-07 22:39 UTC, matthewoates commented on podcast-player/podcast-player-app/src/assets/SVG/circle-right.svg
> +<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
The license will say how you should handle the assets. Some are very forgiving (such as [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) ) which basically means you can do whatever you want and don't need to give credit

2022-03-08 01:47 UTC, matthewoates requested changes
A few more gripes, and after that this is a pass. Nice work with the quick turnaround!

2022-03-08 01:47 UTC, matthewoates commented on podcast-player/src/components/episode/EpisodeDetails.jsx
> +function EpisodeDetails({ episode, setSelectedEpisodePlaying }) {
still have this dead code

2022-03-08 01:47 UTC, matthewoates commented on podcast-player/src/components/episode/EpisodeList.jsx
> +          setFirstTenEpisodes([...data.channel.episodes].slice(0, 9));
Unnecessary shallow copying, but beyond that -

No need to have this all as separate state hooks. You're not copying from props, but there's a similar issue described here: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

You can just save the `data` and use that.

2022-03-08 01:47 UTC, matthewoates commented on podcast-player/src/components/episode/EpisodePlayer.jsx
> +  // const { $length, $type, $url } = content;
There's still commented code. Did you do a self-review pass of your own changes?

2022-03-16 06:25 UTC, merged